image/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from image.views import IndexView
from image.views import UploadImage
from image.views import ListImages
from image.views import MapView
from image.views import DetailImage

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('upload/', UploadImage.as_view(), name='upload'),
    path('list/', ListImages.as_view(), name='list'),
    path('map/', MapView.as_view(), name='map'),
    path('<int:pk>/', DetailImage.as_view(), name='detail'),
]

immap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Index page.
    path('',include(('image.urls','image'))),
]

if settings.DEBUG:
    # Serve media file during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Serve static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

image/models.py
from django.db import models
from django.conf import settings

import os 

# Create your models here.

class SImage(models.Model):

    Model_0 = '0'
    Model_1 = '1'

    MODEL_SELECT = (
        (Model_0, "Random Forest"),
        (Model_1, "Support Vector Machines"),
    )

    WAITING = '0'
    PROCESSING = '1'
    PROCESSED =  '2'
    ERROR = '3'

    PROCESSING_STATUS = (
        (WAITING,'Waiting'),
        (PROCESSING,'Processing'),
        (PROCESSED,'Processed'),
        (ERROR,'Error')
    )

    IDEAM = '0'
    USGS = '1'

    SOURCE = (
        (IDEAM,'Geoscience Datacube'),
        (USGS,'United States Geological Survey USGS')
    )

    LS8_OLI_LARSRC = '0'

    PRODUCT = (
        (LS8_OLI_LARSRC,'LS8_OLI_LASRC'),
    )

    LANDSAT_8 = '0'

    PLATFORM = (
        (LANDSAT_8,'LANDSAT_8'),
    )

    model = models.CharField(max_length=2,choices=MODEL_SELECT,default=Model_0)
    status = models.CharField(max_length=2,choices=PROCESSING_STATUS,default=WAITING)

    product = models.CharField(max_length=2,choices=PRODUCT,default=LS8_OLI_LARSRC)
    platform = models.CharField(max_length=2,choices=PLATFORM,default=LANDSAT_8)

    lat_min = models.CharField(
        'Latitude Min',
        help_text='Valid values 5.276905999999999 - 3.0384721000000003. Example: 3.6667',
        max_length=200
    )
    lat_max = models.CharField(
        'Latitude Max',
        help_text='Valid values 5.276905999999999 - 3.0384721000000003. Example: 3.9084',
        max_length=200
    )
    lon_min = models.CharField(
        'Longitude Min',
        help_text='Valid values -75.80698879999998,-74.491394. Example: -75.0216',
        max_length=200
    )
    lon_max = models.CharField(
        'Longitude Max',
        help_text='Valid values -75.80698879999998,-74.491394. Example: -74.8039',
        max_length=200)

    date_min = models.CharField('Date Min',max_length=20,help_text='Date format AAAA-MM-DD. Example: 2015-01-01')
    date_max = models.CharField('Date Max',max_length=20,help_text='Date format AAAA-MM-DD. Example: 2016-01-01')
    
    def processed_path(self):
        return os.path.join(settings.MEDIA_URL, str(self.id) + '_labeled.png')
    
    def processed_url(self):
        return os.path.join(settings.MEDIA_URL, str(self.id) + '_labeled.png') 

image/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from image.models import SImage

# Create the form class.
class ArticleForm(ModelForm):
    class Meta:
        model = SImage
        exclude = ['status']

image/views.py
from django.shortcuts import render, reverse
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from image.models import SImage
from django.conf import settings

# Create your views here.

from django.views.generic.base import TemplateView

from image.tasks import start_image_processing

import os

class IndexView(TemplateView):

    def get(self,request,*args,**kwargs):
        template_name = 'image/index.html'
        return render(request,template_name)


class MapView(TemplateView):

    def get(self,request,*args,**kwargs):
        template_name = 'image/map.html'
        return render(request,template_name)

class UploadImage(CreateView):
    # Use simage_form.html as template implicity
    model = SImage
    fields = [
        'model','product','platform',
        'lat_min', 'lat_max','lon_min',
        'lon_max','date_min','date_max'
    ]

    def get_success_url(self):
        # return reverse('image:index', kwargs={'pk': self.object.pk})

        datacube_data = {
            'product': self.object.get_product_display(),
            'platform': self.object.get_platform_display(),
            'latitude': (self.object.lat_min,self.object.lat_max),
            'longitude': (self.object.lon_min,self.object.lon_max),
            'time': (self.object.date_min,self.object.date_max)
        }
        
        image_data = {
            'id': self.object.id,
            'original_path': os.path.join(settings.MEDIA_ROOT, str(self.object.id) + '.png' ),
            'classified_path': os.path.join(settings.MEDIA_ROOT, str(self.object.id) + '_labeled.png') 
        }

        db_data = {
            'database_name': settings.DATABASES['default']['NAME']
        }

        # "Random Forest"
        if self.object.model == SImage.Model_0:
            model_data = {
                'path': os.path.join(settings.MEDIA_ROOT,'RF.joblib')
            }
        # "Support Vector Machines"
        else:
            model_data = {
                'path': os.path.join(settings.MEDIA_ROOT,'SVM.joblib')
            }
        
        # Start image processing
        start_image_processing.delay(datacube_data,image_data,model_data,db_data)

        return reverse('image:list')

class ListImages(ListView):
    # Use simage_list.html as template implicity
    model = SImage


class DetailImage(DetailView):
    # Use simage_detail.html as template implicity
    model = SImage

image/templates/image/index.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
</head>
<body>

<div class="sidenav">
  <a href="{% url 'image:index' %}">Home</a>
  <a href="{% url 'image:upload' %}">Classify</a>
  <a href="{% url 'image:list' %}">Images</a>
</div>


<div class="container" style="max-width: 70%; align-content: center; margin-left: 15%; margin-bottom: 5%; margin-top: 5%">
<header class="section-header">
          <h1 style="text-align: center;">Metodología para el monitoreo de cultivos a partir de imágenes satelitales con Machine Learning.</h1>
          <h7>El desarrollo de esta metodología permitió la integración de los procesos de teledetección, análisis, clasificación e implementación de algoritmos de aprendizaje automático en infraestructuras que toleran procesamiento sobre big data cómo el Open Data Cube (ODC). Esta metodología integra la creación de un modelo que permite clasificar 9 clases de cobertura terrestre y el cultivo del arroz (Orytza sativa)  en 4 etapas fenológicas. Además contempla  la infraestructura del ODC para el procesamiento masivo enfocado en análisis de series de tiempo.</h7>
          <h7>A partir de la metodología contruida se desarrolla la siguiente infografía para el análisis e implementación de estas etápas en diferentes aplicaciones. Esta metodología es escalable y puede ser aplicada en diferentes dominios. La infografía es la siguiente:</h7>


        <img src="/media/metodologia.jpg" alt="Italian Trulli" style="max-width: 70%; align-items: center; margin-left: 15%; margin-right: 15%; margin-bottom: 5%; margin-top: 5%">

        <br><br><br>
        <h7>A partir de los datos compartidos por el Banco Agrario, fue posible desarrollar una visualización que permitió la integración de la inversión generada en varios municipios del departamento del Tolima. De esta manera, se hace un análisis por un periodo de 3 años desde Enero del 2017 hasta Agosto del 2019. Estos datos nos permitió seleccionar la zona definitiva de interés e interactuar con la misma. En esta visualización es posible ratificar las fechas en las que inicial el proceso del cultivo. También, fue posible identificar que el municipio de Venadillo recibió un aumento exponencial en la inversión generada el último año. Sin embargo, debido a que no se había generado de manera periódica se descartó del área de interés. Un factor que fortaleció esta decisión fue identificar que en esta parte del Tolima predomina el cultivo del café, esto permitió identificar que las inversiones generadas podrían ser distribuidas en un cultivo diferente. 
En la sifguiente visualización se presenta la pantalla principal de la visualización, este recurso permite la interacción de los usuarios y la detección de datos atípicos importantes para el análisis descriptivo de la inversión generada en el Departamento. Así como la selección de las áreas de interés.</h7>

        <h7>En la etapa de investigación de dominio se desarrolla una visualización con el fin de abstraer las propiedades y acaracterísticas específicas del territorio. En esta fase se crea la siguiente visualización interactiva a partir de los datos proporcionados por el Banco Agrario:</h7>

        <br><br><br>

        <div class='tableauPlaceholder' id='viz1593585853878' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;An&#47;AnlisisDatosTesis&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='AnlisisDatosTesis&#47;Dashboard1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;An&#47;AnlisisDatosTesis&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='es' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1593585853878');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='1877px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>


        

        <br><br><br>

</header>
</div>
   
</body>
</html> 

image/templates/image/map.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
</head>
<body>

<div class="sidenav">
  <a href="{% url 'image:index' %}">Home</a>
  <a href="{% url 'image:upload' %}">Classify</a>
  <a href="{% url 'image:list' %}">Images</a>
</div>

<div id="map" class="main"></div>

<script>
  var historicalOverlay;

  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 13,
      center: {lat: 40.740, lng: -74.18}
    });

    // var imageBounds = {
    //   north: 40.773941,
    //   south: 40.712216,
    //   east: -74.12544,
    //   west: -74.22655
    // };

//     var imageBounds = {
//       north: 12.000094413,
//       south: 11.000075240999998,
//       east: -71.9999716425,
//       west: -73.0000331225
//     };

//     historicalOverlay = new google.maps.GroundOverlay(
//         'example.png',
//         imageBounds);
//     historicalOverlay.setMap(map);
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwEW9_KvS6Kc9mphuIsGcnUb_Kx57UKtU&callback=initMap"
async defer></script>
   
</body>
</html> 

image/templates/image/simage_detail.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
</head>
<body>

<div class="sidenav">
  <a href="{% url 'image:index' %}">Home</a>
  <a href="{% url 'image:upload' %}">Classify</a>
  <a href="{% url 'image:list' %}">Images</a>
</div>

<img src="{{ object.processed_url }}" alt="Italian Trulli" style="max-width: 70%; align-items: center; margin-left: 15%; margin-right: 15%; margin-bottom: 5%; margin-top: 5%">
 
  
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;margin:0px auto;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-u01j{background-color:#34cdf9;border-color:inherit;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-96sx{background-color:#00d2cb;border-color:inherit;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-dlbm{background-color:#34cdf9;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;margin: auto 0px;}}</style>
<div class="tg-wrap"><table class="tg">
<thead>
  <tr>
    <th class="tg-96sx">{{ object.get_model_display }}</th>
    <th class="tg-u01j">Mínimo</th>
    <th class="tg-u01j">Máximo</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-u01j">Latitud</td>
    <td class="tg-0pky">{{ object.lat_min }}</td>
    <td class="tg-0pky">{{ object.lat_max }}</td>
  </tr>
  <tr>
    <td class="tg-u01j">Longitud</td>
    <td class="tg-0pky">{{ object.lon_min }}</td>
    <td class="tg-0pky">{{ object.lon_max }}</td>
  </tr>
  <tr>
    <td class="tg-dlbm">Fecha</td>
    <td class="tg-0lax">{{ object.date_min }}</td>
    <td class="tg-0lax">{{ object.date_max }}</td>
  </tr>
</tbody>
</table></div>
  



  
</body>
</html> 

image/templates/image/simage_form.html
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

.help-block {
  font-size: 12;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
</head>
<body>

<div class="sidenav">
  <a href="{% url 'image:index' %}">Home</a>
  <a href="{% url 'image:upload' %}">Classify</a>
  <a href="{% url 'image:list' %}">Images</a>
</div>

<div class="main">
  <section class="main-container">
  <div class="container">
      <div class="row">

        <!-- main start -->
        <!-- ================ -->
        <div class="main col-md-8">
        <br><br>
        <div class="separator-2"></div>
          <div class="section light-gray-bg">
            <div class="container">
              <!-- <form role="form" class="form-horizontal col-md-5 col-md-offset-1" method="POST" enctype="multipart/form-data"> -->
              <form role="form" class="form-horizontal col-md-10" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' error_types="all" %}
                {% buttons %}
                <!-- <div class="text-center"> -->
                  <button type="submit" class="btn btn-default col-md-offset-11">
                     Enviar
                  </button>
                <!-- </div> -->
                {% endbuttons %}
              </form>
            </div>
          </div>
        </div>
        <!-- main end -->
      </div>
    </div>
  </section>
  <!-- main-container end -->   
</body>
</html> 

image/templates/image/simage_list.html
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
</head>
<body>

<div class="sidenav">
  <a href="{% url 'image:index' %}">Home</a>
  <a href="{% url 'image:upload' %}">Classify</a>
  <a href="{% url 'image:list' %}">Images</a>
</div>

<!-- <div class="main"> -->
  <!-- <section class="main-container"> -->
  <div class="container">
      <!-- <div class="row"> -->

        <!-- main start -->
        <!-- ================ -->
        <div class="main col-md-10">
        <br><br>
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Processed</th>
                <th scope="col">Model</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
              <tr>
                <th scope="row"><a class="btn btn-primary" href="{% url 'image:detail' object.pk %}" role="button">{{ object.id }}</a></th>
                <td>{{ object.upload.name }}</td>
                <td>{{ object.processed_path }}</td>
                <td>{{ object.get_model_display }}</td>
                <td>{{ object.get_status_display }}</td>
                <td>
                  {% if object.get_status_display in "Processed" %}
                  <a class="btn btn-primary" href="{% url 'image:detail' object.pk %}" role="button"><i class="glyphicon glyphicon-eye-open"></i></a>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
        <!-- main end -->
      <!-- </div> -->
    </div>
  <!-- </section> -->
  <!-- main-container end -->   
</body>
</html> 

templates/map.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
</head>
<body>

<div class="sidenav">
  <a href="#contact">Home</a>
  <a href="{% url 'image:upload' %}">Upload</a>
  <a href="{% url 'image:list' %}">Images</a>
</div>

<div id="map" class="main"></div>

<script>
  var historicalOverlay;

  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 13,
      center: {lat: 40.740, lng: -74.18}
    });

    // var imageBounds = {
    //   north: 40.773941,
    //   south: 40.712216,
    //   east: -74.12544,
    //   west: -74.22655
    // };

    var imageBounds = {
      north: 12.000094413,
      south: 11.000075240999998,
      east: -71.9999716425,
      west: -73.0000331225
    };

    historicalOverlay = new google.maps.GroundOverlay(
        'example.png',
        imageBounds);
    historicalOverlay.setMap(map);
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBwEW9_KvS6Kc9mphuIsGcnUb_Kx57UKtU&callback=initMap"
async defer></script>
   
</body>
</html> 